services:
  dev:
    container_name: store-inventory-and-sales-manager-web_c
    image: store-inventory-and-sales-manager-web_i
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    command: pnpm run dev
